name: 🚀 Release

on:
  push:
    branches:
      - main

env:
  HUSKY: 0
  CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.full_name == github.repository }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci -w zksync-easy-onramp --include-workspace-root

      - name: Create Release PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore(changeset): version packages"
          commit: "chore(changeset): version packages"
          publish: npm run publish-package
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_NPM_MATTERLABS_AUTOMATION_TOKEN }}
