name: 🚀 Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: write # changesets pushes the version branch and creates GitHub releases/tags
  pull-requests: write # changesets opens/updates the "version packages" PR

env:
  HUSKY: 0
  CI: true
  PUBLISH: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.full_name == github.repository }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4

      - name: Update npm for OIDC support
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: npm ci -w zksync-easy-onramp --include-workspace-root

      - name: Create Release PR or Publish to NPM
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5
        with:
          title: "chore(changeset): version packages"
          commit: "chore(changeset): version packages"
          publish: npm run publish-package --access public --provenance
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
